# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7ON_jduNxOVODkcmYqhKv5-2rWD5vg8
"""
import pandas as pd
import numpy as np
from asyncio import run
from flask import app
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import streamlit as st

# Load the data
df10 = pd.read_csv('/workspaces/bangalorerealestate/my_data.csv')
locations = df10['location'].unique().tolist()
df10 = pd.read_csv('/workspaces/bangalorerealestate/my_data.csv', usecols=lambda column: column != 'location')



# Split data into features (X) and target (y)
X = df10.drop(['price'], axis='columns')
y = df10.price

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Function to preprocess user input and make predictions
def predict_price(location, sqft, bath, bhk, model, X):
    loc_index = np.where(X.columns == location)[0][0] if location in X.columns else -1

    x = np.zeros(len(X.columns))
    x[0] = sqft
    x[1] = bath
    x[2] = bhk
    if loc_index >= 0:
        x[loc_index] = 1

    return model.predict([x])[0]

import streamlit as st
# Streamlit app
st.title('Property Price Predictor')

# Input fields
locations = locations
location = st.selectbox('Select Location', locations)
total_sqft = st.number_input('Total Square Feet', value=1000)
bath = st.number_input('Number of Bathrooms', value=2)
bhk = st.number_input('Number of Bedrooms (BHK)', value=2)

# Predict button
if st.button('Predict Price'):
    predicted_price = predict_price(location, total_sqft, bath, bhk, model, X)
    st.success(f'Predicted Price in Lakh Rupees: {predicted_price}')
